### ISSUE TITLE
Better way to get free RAM / heap

### ISSUE THREAD

**Issue by CHiPs44** [CHiPs44/hagl_pico_vgaboard#21]
cf. <https://forums.raspberrypi.com/viewtopic.php?t=347638#p2082565>

**Comment by CHiPs44** [comment]
Malloc dichotomy: 147437
This method: 151376
From map file:  169136 (0x294B0 = 0x20040000 - 0x20016b50)

```
$ grep __bss_end__ *.map
                0x0000000020016b50                __bss_end__ = .
$ grep __StackLimit *.map
                0x0000000020040000                __StackLimit = (ORIGIN (RAM) + LENGTH (RAM))
                0x0000000000000001                ASSERT ((__StackLimit >= __HeapLimit), region RAM overflowed)
```

**Comment by tuupola** [comment]
Interesting why the difference. I also use the forum method [here](https://github.com/tuupola/pico_effects/blob/master/main.c#L72-L86).
