### ISSUE TITLE
Feasibility to use image Huffman compression for more color availability

### ISSUE THREAD

**Issue by mlorenzati** [CHiPs44/hagl_pico_vgaboard#7]
I'm seeing an excellent work towards video scanline generation with framebuffer, that gets limited by current rpi memory footprint.
My question would be if its possible to create a virtual 640x480 multicolor space using huffman compression to allow direct usage of this framebuffer.

**Comment by CHiPs44** [comment]
Timings in the render loop are very short, uncompressing won't be doable, I think.
